In [2]:
import pandas as pd

In [3]:
variable=pd.read_csv("./modulo-2-equipo-1")
variable= pd.read_excel("ruta_donde_esta _el_fichero")
variable= pd.read_json("ruta_donde_esta _el_fichero")

FileNotFoundError: [Errno 2] No such file or directory: './modulo-2-equipo-1'

In [ ]:
## leer un json

df_one_piece=pd.read_json("./one_piece.json")

In [ ]:
df_one_piece

,rank,trend,season,episode,name,start,total_votes,average_rating
0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [ ]:
df_one_piece.tail(3)

,rank,trend,season,episode,name,start,total_votes,average_rating
3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
5,"36,209",4,1,6,Desperate Situation! Beast Tamer Mohji vs. Luffy!,1999,364,7.7

In [ ]:
df_one_piece.columns

Index(['rank', 'trend', 'season', 'episode', 'name', 'start', 'total_votes',
       'average_rating'],
      dtype='object')

In [ ]:
books=pd.read_xml("./books.xml",parser="etree")

In [ ]:
books

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
2,bk103,"Corets, Eva",Maeve Ascendant,Fantasy,5.95,2000-11-17,After the collapse of a nanotechnology \n ...
3,bk104,"Corets, Eva",Oberon's Legacy,Fantasy,5.95,2001-03-10,"In post-apocalypse England, the mysterious \n ..."
4,bk105,"Corets, Eva",The Sundered Grail,Fantasy,5.95,2001-09-10,"The two daughters of Maeve, half-sisters, \n ..."
5,bk106,"Randall, Cynthia",Lover Birds,Romance,4.95,2000-09-02,When Carla meets Paul at an ornithology \n ...
6,bk107,"Thurman, Paula",Splish Splash,Romance,4.95,2000-11-02,A deep sea diver finds true love twenty \n ...
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
8,bk109,"Kress, Peter",Paradox Lost,Science Fiction,6.95,2000-11-02,After an inadvertant trip through a Heisenberg...
9,bk110,"O'Brien, Tim",Microsoft .NET: The Programming Bible,Computer,36.95,2000-12-09,Microsoft's .NET initiative is explored in \n ...
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

In [ ]:
## leer excel
df_libros= pd.read_excel("./libros_ejemplo.xlsx")

In [ ]:
df_clientes=pd.read_csv("./clientes.csv")

In [ ]:
df_clientes

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,"5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
995,996,Ray,Tarpey,rtarpeyrn@bravesites.com,Female,Zamora,Spain,36384 Sommers Terrace
996,997,Flem,Roderham,froderhamro@dropbox.com,Male,Pontevedra,Spain,93177 Eastwood Parkway
997,998,Winifield,Blakes,wblakesrp@jiathis.com,Male,Vigo,Spain,03044 Grayhawk Road
998,999,Lanita,Espinosa,lespinosarq@discuz.net,Female,Dos Hermanas,Spain,2 Schmedeman Drive
999,1000,Grissel,Siberry,gsiberryrr@wikispaces.com,Female,Leon,Spain,42274 Waywood Terrace

In [ ]:
df_clientes.isnull().sum()

id              0
first_name     52
last_name      52
email          77
gender        123
City          176
Country       200
Address        91
dtype: int64

In [ ]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   object
 1   first_name  948 non-null    object
 2   last_name   948 non-null    object
 3   email       923 non-null    object
 4   gender      877 non-null    object
 5   City        824 non-null    object
 6   Country     800 non-null    object
 7   Address     909 non-null    object
dtypes: object(8)
memory usage: 62.6+ KB

In [4]:
df_christmas=pd.read_csv("./christmas_movies.csv")

## CONECTAR SQL

# conectar son SQL
# crear BD
# Insertar
#realizar consultas a BD

In [8]:
import mysql.connector
from mysql.connector import Error

try:
    cnx=connection = mysql.connector.connect(
        host='127.0.0.1',
        user='root',
        password='?10101948SanMartin',
        
    )
    print('Conexión exitosa')
except Error as e:
    print('Error al conectar:', e)

Conexión exitosa

## crear BD

In [9]:
try:
    mycursor = cnx.cursor()
    query = "CREATE DATABASE IF NOT EXISTS christmas"
    mycursor.execute(query)
    print("Query exitosa")
except:
    print("Error.")

Query exitosa

# crear tabla

In [10]:
mycursor.execute("USE christmas")

query = '''CREATE TABLE christmas_movies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    rating VARCHAR(20),
    runtime INT,
    imdb_rating DECIMAL(3,1),
    meta_score INT,
    genre VARCHAR(255),
    release_year INT,
    description TEXT,
    director VARCHAR(255),
    stars TEXT,
    votes VARCHAR(50),
    gross VARCHAR(50),
    img_src VARCHAR(500),
    type VARCHAR(50)
);'''

mycursor.execute(query)

In [15]:
import numpy as np

# 3. Insertar
# Query de inserción
query_insert = """
INSERT INTO christmas_movies (title, rating, runtime, imdb_rating, meta_score, 
                              genre, release_year, description, director, stars, 
                              votes, gross, img_src, type) 
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

df_clean = df_christmas.replace({np.nan: None, 'nan': None, 'NaN': None})

datos = df_clean.values.tolist()

# Ejecutar inserción
mycursor.executemany(query_insert, datos)
cnx.commit()

print(f"{mycursor.rowcount} registros insertados")

print(f"{mycursor.rowcount} registros insertados")

873 registros insertados
873 registros insertados